# Generated by Django 3.1.5 on 2021-08-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp1', '0002_userrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRating',
        ),
        migrations.AddField(
            model_name='userreview',
            name='star_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
