# Generated by Django 3.1.5 on 2021-08-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp1', '0003_auto_20210810_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='ari',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userreview',
            name='avg',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userreview',
            name='cli',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userreview',
            name='review_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
