# Generated by Django 3.1.5 on 2021-09-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp1', '0004_auto_20210830_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='prolific_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
