# Generated by Django 3.1.5 on 2021-09-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp1', '0006_userreview500char_userreviewnoindicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
